[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Art Of Resilience In The Workplace: Techniques For Overcoming Adversity And Thriving In A Changing Environment"
